apiVersion: v1
kind: Service
metadata:
  name: learnhub-service
  namespace: learnhub
spec:
  type: NodePort
  selector:
    app: learnhub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007